describe("Calculator Tool", function()
    local Calculator

    setup(function()
        Calculator = require("dslua.tools.builtin.calculator")
    end)

    it("should create calculator", function()
        local calc = Calculator.new()
        assert.is.equal("calculator", calc:Name())
        assert.is.equal("Performs arithmetic operations: add, subtract, multiply, divide", calc:Description())
    end)

    it("should add two numbers", function()
        local calc = Calculator.new()
        local result = calc:Execute({operation = "add", a = 5, b = 3})
        assert.is.equal(8, result)
    end)

    it("should subtract two numbers", function()
        local calc = Calculator.new()
        local result = calc:Execute({operation = "subtract", a = 10, b = 4})
        assert.is.equal(6, result)
    end)

    it("should multiply two numbers", function()
        local calc = Calculator.new()
        local result = calc:Execute({operation = "multiply", a = 6, b = 7})
        assert.is.equal(42, result)
    end)

    it("should divide two numbers", function()
        local calc = Calculator.new()
        local result = calc:Execute({operation = "divide", a = 20, b = 4})
        assert.is.equal(5, result)
    end)

    it("should handle division by zero", function()
        local calc = Calculator.new()
        assert.has_error(function()
            calc:Execute({operation = "divide", a = 10, b = 0})
        end, "Division by zero")
    end)

    it("should handle non-numeric input", function()
        local calc = Calculator.new()
        local result = calc:Execute({operation = "add", a = "5", b = "3"})
        assert.is.equal(8, result)
    end)

    it("should throw error for unknown operation", function()
        local calc = Calculator.new()
        assert.has_error(function()
            calc:Execute({operation = "modulo", a = 10, b = 3})
        end, "Unknown operation: modulo")
    end)

    it("should throw error when missing parameters", function()
        local calc = Calculator.new()
        assert.has_error(function()
            calc:Execute({operation = "add", a = 5})
        end)
    end)
end)
